export const SORTED_LEVELS = {
  1: 'South.Post-Chalcolithic',
  2: 'North.Post-Chalcolithic',
  3: 'TPC.Post-Chalcolithic',
  4: 'Trench 1.Chalcolithic',
  5: 'Trench 5.Chalcolithic',
  6: 'TP.Z',
  7: 'TP.W',
  8: 'TPC.W',
  9: 'TP.U',
  10: 'TPC.U',
  11: 'TP.S',
  12: 'TPC.S',
  13: 'TP.R',
  14: 'TP.Q',
  15: 'TPC.Q',
  16: 'TP.P',
  17: 'TP.O',
  18: 'TP.N',
  19: 'TPC.N',
  20: 'TP.M',
  21: 'TPC.M',
  22: 'South.T',
  23: 'South.?T',
  24: 'South.S',
  25: 'South.R',
  26: 'South.Q',
  27: 'North.J',
  28: 'North.I',
  29: 'South.P',
  30: 'South.?P',
  31: 'North.H',
  32: 'North.?H',
  33: 'South.O',
  34: 'North.G',
  35: 'North.?G',
  36: 'South.N',
  37: 'South.?N',
  38: 'South.M',
  39: 'South.?M',
  40: 'South.L',
  41: 'South.?L',
  42: 'North.F',
  43: 'South.K',
  44: 'South.?K',
  45: 'South.J',
  46: 'South.?I',
  47: 'South.H',
  48: 'South.?H',
  49: 'South.G',
  50: 'South.Unstratified Neolithic',
  51: 'North.Unstratified Neolithic',
  52: 'IST.Unassigned',
  53: 'South.Unknown',
  54: 'North.Unknown',
  55: 'TPC.Unknown',
  56: '?',
  57: 'NULL'
}
